services:
  app:
    image: &app_image ghcr.io/tanyaflos76/flask-project:latest

    volumes: &app_volumes
      - ./data:/app/data
      - ./uploads:/app/uploads

    restart: unless-stopped

    env_file: &app_env_file
      - .env

    depends_on:
      migrations:
        condition: service_started

    healthcheck: &healthcheck
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 2s
      start_interval: 1s

    ports:
      - 8080:8080

  migrations:
    image: *app_image

    volumes: *app_volumes

    env_file: *app_env_file

    command: "python -m alembic upgrade head"

    healthcheck:
      disable: true
