"""Add is_taken column

Revision ID: 7601fcfd91ec
Revises: 865dccb26feb
Create Date: 2025-04-16 14:55:27.526587+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7601fcfd91ec"
down_revision: Union[str, None] = "865dccb26feb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wishes", sa.Column("is_taken", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wishes", "is_taken")
