"""empty message

Revision ID: 08026628f781
Revises: 0ceaf42e882f
Create Date: 2025-04-20 16:56:41.206427+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08026628f781'
down_revision: Union[str, None] = '0ceaf42e882f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishes', 'link')
    # ### end Alembic commands ###
